title: Cyril Focht
subtitle: Data Analytics Consultant

author: Cyril Focht
email: cyril.focht@gmail.com
avatar: assets/avatar.jpg

baseurl: ""
url: "https://cyrilfocht.github.io/"

linkedin_url: https://www.linkedin.com/in/cyril-focht/

plugins:
  - jekyll-font-awesome-sass
  - jekyll-sitemap
  - jekyll-feed

repository: cyrilfocht/cyrilfocht.github.io
remote_theme: chrisbobbe/jekyll-theme-prologue
collections:
    - sections
    - projects
    - resume