title: Cyril Focht
subtitle: I make games

author: Cyril Focht
email: cfocht@ucsc.edu
avatar: assets/avatar.jpg

linkedin_url: https://www.linkedin.com/in/cyril-focht-586b37156/
twitter_url: https://twitter.com/gamesandbowties

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
